"""Assemble the canonical ``examples/<kernel>/`` artifact for the hub repo.

Mirrors the flydsl-kernel-profiling bundle layout so any machine (no GPU) can
clone and load the ATT dirs into rocprof-compute-viewer or read the report:

    examples/<kernel>/
    ├── README.md            (repro command + layout note)
    ├── REPORT.md            (copied from the run)
    ├── att_viewer/<tag>/ui_output_agent_*_dispatch_*/
    ├── compute_viewer/      (counters.json + *_out_results.json + *_agent_info.csv)
    └── source/              (kernel .py + report.json/headlines.json)
"""
from __future__ import annotations

import shutil
from pathlib import Path

from .envelope import FlyprofError, Result


def cmd_bundle(args, cfg) -> Result:
    bundle = cfg.require_bundle()
    capture = cfg.read_artifact("capture.json")
    kernel = capture.get("recipe_kernel") or capture.get("kernel", "kernel")
    examples = Path(cfg.examples_dir)
    dest = examples / kernel
    if dest.exists() and getattr(args, "no_clobber", False):
        raise FlyprofError("BAD_ARGS", f"{dest} exists and --no-clobber set",
                           help="remove --no-clobber or choose another --examples-dir")
    (dest / "att_viewer").mkdir(parents=True, exist_ok=True)
    (dest / "compute_viewer").mkdir(parents=True, exist_ok=True)
    (dest / "source").mkdir(parents=True, exist_ok=True)

    copied = {"att": [], "compute_viewer": [], "source": []}
    # ATT dirs per tag
    for tag, tinfo in (capture.get("tags") or {}).items():
        kept = tinfo.get("kept_dir")
        if not kept:
            continue
        src = bundle / kept
        if src.exists():
            dst = dest / "att_viewer" / tag / src.name
            shutil.rmtree(dst, ignore_errors=True)
            shutil.copytree(src, dst)
            copied["att"].append(f"{tag}/{src.name}")
    # compute-viewer support + counters
    for pat in ("*_out_results.json", "*_agent_info.csv", "counters.json"):
        for f in bundle.glob(pat):
            shutil.copy(f, dest / "compute_viewer" / f.name)
            copied["compute_viewer"].append(f.name)
    # report + json siblings
    for name in ("REPORT.md", "report.json", "headlines.json"):
        f = bundle / name
        if f.exists():
            shutil.copy(f, dest / name if name == "REPORT.md" else dest / "source" / name)
    # kernel source from the worktree
    for cand in (cfg.worktree / "kernels" / f"{kernel}.py",
                 cfg.worktree / "kernels" / f"{kernel}_kernel.py"):
        if cand.exists():
            shutil.copy(cand, dest / "source" / cand.name)
            copied["source"].append(cand.name)

    readme = dest / "README.md"
    readme.write_text(
        f"# {kernel} — gfx950/MI350X profiling bundle\n\n"
        f"Generated by `flyprof bundle`. Load `att_viewer/<tag>/ui_output_*` into "
        f"rocprof-compute-viewer, or read `REPORT.md`.\n\n"
        f"Repro: `flyprof run {kernel} --gpu 0`\n"
    )
    data = {"kernel": kernel, "examples_dir": str(dest), "copied": copied}
    return Result(data=data, bundle=str(bundle))
